server:
  name: "project-user"
  port: "127.0.0.1:10001"
grpc:
  addr: "127.0.0.1:11001"
  name: "project-user"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:12379"
zap:
  debugFileName: "D:\\Environment\\Go\\gopath\\src\\ProjectManagement\\logs\\debug\\debug.log"
  infoFileName: "D:\\Environment\\Go\\gopath\\src\\ProjectManagement\\logs\\info\\info.log"
  warnFileName: "D:\\Environment\\Go\\gopath\\src\\ProjectManagement\\logs\\warn\\warn.log"
  maxAge: 28
  maxSize: 500
  maxBackups: 3
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
mysql:
  username: root
  password: spx@yp
  host: 127.0.0.1
  port: 3309
  db: project_management
  tablePrefix: "pm_"
jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: g2r3fa
  refreshSecret: 13f3ah