server:
  name: "project-user"
  port: "0.0.0.0:9001"
grpc:
  addr: "0.0.0.0:9501"
  name: "project-user"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "etcd3:2379"
zap:
  debugFileName: "/logs/debug/debug.log"
  infoFileName: "/logs/info/info.log"
  warnFileName: "/logs/warn/warn.log"
  maxAge: 28
  maxSize: 500
  maxBackups: 3
redis:
  host: "redis6"
  port: 6379
  password: ""
  db: 0
mysql:
  username: root
  password: spx@yp
  host: 172.17.0.1
  port: 3309
  db: project_management
  tablePrefix: "pm_"
jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: g2r3fa
  refreshSecret: 13f3ah