server:
  name: "project-project-grpc"
  port: "0.0.0.0:8887"
grpc:
  addr: "0.0.0.0:8888"
  name: "project-grpc"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "etcd3:2379"
zap:
  debugFileName: "/logs/debug/debug.log"
  infoFileName: "/logs/info/info.log"
  warnFileName: "/logs/warn/warn.log"
  maxAge: 28
  maxSize: 500
  maxBackups: 3
redis:
  host: "redis6"
  port: 6379
  password: ""
  db: 0