// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: department_service.proto

package department

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DepartmentServiceClient is the client API for DepartmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DepartmentServiceClient interface {
	SaveDepartment(ctx context.Context, in *DepartmentRpcRequest, opts ...grpc.CallOption) (*Department, error)
	GetDepartmentList(ctx context.Context, in *DepartmentRpcRequest, opts ...grpc.CallOption) (*ListDepartment, error)
	ReadDepartment(ctx context.Context, in *DepartmentRpcRequest, opts ...grpc.CallOption) (*Department, error)
}

type departmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDepartmentServiceClient(cc grpc.ClientConnInterface) DepartmentServiceClient {
	return &departmentServiceClient{cc}
}

func (c *departmentServiceClient) SaveDepartment(ctx context.Context, in *DepartmentRpcRequest, opts ...grpc.CallOption) (*Department, error) {
	out := new(Department)
	err := c.cc.Invoke(ctx, "/department.service.DepartmentService/SaveDepartment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentServiceClient) GetDepartmentList(ctx context.Context, in *DepartmentRpcRequest, opts ...grpc.CallOption) (*ListDepartment, error) {
	out := new(ListDepartment)
	err := c.cc.Invoke(ctx, "/department.service.DepartmentService/getDepartmentList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentServiceClient) ReadDepartment(ctx context.Context, in *DepartmentRpcRequest, opts ...grpc.CallOption) (*Department, error) {
	out := new(Department)
	err := c.cc.Invoke(ctx, "/department.service.DepartmentService/ReadDepartment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepartmentServiceServer is the server API for DepartmentService service.
// All implementations must embed UnimplementedDepartmentServiceServer
// for forward compatibility
type DepartmentServiceServer interface {
	SaveDepartment(context.Context, *DepartmentRpcRequest) (*Department, error)
	GetDepartmentList(context.Context, *DepartmentRpcRequest) (*ListDepartment, error)
	ReadDepartment(context.Context, *DepartmentRpcRequest) (*Department, error)
	mustEmbedUnimplementedDepartmentServiceServer()
}

// UnimplementedDepartmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDepartmentServiceServer struct {
}

func (UnimplementedDepartmentServiceServer) SaveDepartment(context.Context, *DepartmentRpcRequest) (*Department, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveDepartment not implemented")
}
func (UnimplementedDepartmentServiceServer) GetDepartmentList(context.Context, *DepartmentRpcRequest) (*ListDepartment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartmentList not implemented")
}
func (UnimplementedDepartmentServiceServer) ReadDepartment(context.Context, *DepartmentRpcRequest) (*Department, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadDepartment not implemented")
}
func (UnimplementedDepartmentServiceServer) mustEmbedUnimplementedDepartmentServiceServer() {}

// UnsafeDepartmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepartmentServiceServer will
// result in compilation errors.
type UnsafeDepartmentServiceServer interface {
	mustEmbedUnimplementedDepartmentServiceServer()
}

func RegisterDepartmentServiceServer(s grpc.ServiceRegistrar, srv DepartmentServiceServer) {
	s.RegisterService(&DepartmentService_ServiceDesc, srv)
}

func _DepartmentService_SaveDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).SaveDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/department.service.DepartmentService/SaveDepartment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).SaveDepartment(ctx, req.(*DepartmentRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentService_GetDepartmentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).GetDepartmentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/department.service.DepartmentService/getDepartmentList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).GetDepartmentList(ctx, req.(*DepartmentRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentService_ReadDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).ReadDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/department.service.DepartmentService/ReadDepartment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).ReadDepartment(ctx, req.(*DepartmentRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DepartmentService_ServiceDesc is the grpc.ServiceDesc for DepartmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepartmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "department.service.DepartmentService",
	HandlerType: (*DepartmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveDepartment",
			Handler:    _DepartmentService_SaveDepartment_Handler,
		},
		{
			MethodName: "getDepartmentList",
			Handler:    _DepartmentService_GetDepartmentList_Handler,
		},
		{
			MethodName: "ReadDepartment",
			Handler:    _DepartmentService_ReadDepartment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "department_service.proto",
}
