// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: project_service.proto

package project

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectServiceClient interface {
	Index(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IndexResponse, error)
	GetProjectList(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*ProjectRpcResponse, error)
	GetProjectTemplates(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*ProjectTemplateResponse, error)
	SaveProject(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*SaveProjectResponse, error)
	ReadProject(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*ReadProjectResponse, error)
	UpdateProjectDeleted(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateProjectCollected(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	EditProject(ctx context.Context, in *EditProjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetLogBySelfProject(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*ProjectLogResponse, error)
	GetNodeList(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*ProjectNodeResponse, error)
	FindProjectByMemberId(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*FindProjectByMemberIdResponse, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) Index(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IndexResponse, error) {
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, "/project.service.ProjectService/Index", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectList(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*ProjectRpcResponse, error) {
	out := new(ProjectRpcResponse)
	err := c.cc.Invoke(ctx, "/project.service.ProjectService/GetProjectList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectTemplates(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*ProjectTemplateResponse, error) {
	out := new(ProjectTemplateResponse)
	err := c.cc.Invoke(ctx, "/project.service.ProjectService/GetProjectTemplates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) SaveProject(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*SaveProjectResponse, error) {
	out := new(SaveProjectResponse)
	err := c.cc.Invoke(ctx, "/project.service.ProjectService/SaveProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ReadProject(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*ReadProjectResponse, error) {
	out := new(ReadProjectResponse)
	err := c.cc.Invoke(ctx, "/project.service.ProjectService/ReadProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProjectDeleted(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/project.service.ProjectService/UpdateProjectDeleted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProjectCollected(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/project.service.ProjectService/UpdateProjectCollected", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) EditProject(ctx context.Context, in *EditProjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/project.service.ProjectService/EditProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetLogBySelfProject(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*ProjectLogResponse, error) {
	out := new(ProjectLogResponse)
	err := c.cc.Invoke(ctx, "/project.service.ProjectService/GetLogBySelfProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetNodeList(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*ProjectNodeResponse, error) {
	out := new(ProjectNodeResponse)
	err := c.cc.Invoke(ctx, "/project.service.ProjectService/GetNodeList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) FindProjectByMemberId(ctx context.Context, in *ProjectRpcRequest, opts ...grpc.CallOption) (*FindProjectByMemberIdResponse, error) {
	out := new(FindProjectByMemberIdResponse)
	err := c.cc.Invoke(ctx, "/project.service.ProjectService/FindProjectByMemberId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations must embed UnimplementedProjectServiceServer
// for forward compatibility
type ProjectServiceServer interface {
	Index(context.Context, *emptypb.Empty) (*IndexResponse, error)
	GetProjectList(context.Context, *ProjectRpcRequest) (*ProjectRpcResponse, error)
	GetProjectTemplates(context.Context, *ProjectRpcRequest) (*ProjectTemplateResponse, error)
	SaveProject(context.Context, *ProjectRpcRequest) (*SaveProjectResponse, error)
	ReadProject(context.Context, *ProjectRpcRequest) (*ReadProjectResponse, error)
	UpdateProjectDeleted(context.Context, *ProjectRpcRequest) (*emptypb.Empty, error)
	UpdateProjectCollected(context.Context, *ProjectRpcRequest) (*emptypb.Empty, error)
	EditProject(context.Context, *EditProjectRequest) (*emptypb.Empty, error)
	GetLogBySelfProject(context.Context, *ProjectRpcRequest) (*ProjectLogResponse, error)
	GetNodeList(context.Context, *ProjectRpcRequest) (*ProjectNodeResponse, error)
	FindProjectByMemberId(context.Context, *ProjectRpcRequest) (*FindProjectByMemberIdResponse, error)
	mustEmbedUnimplementedProjectServiceServer()
}

// UnimplementedProjectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProjectServiceServer struct {
}

func (UnimplementedProjectServiceServer) Index(context.Context, *emptypb.Empty) (*IndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Index not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectList(context.Context, *ProjectRpcRequest) (*ProjectRpcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectList not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectTemplates(context.Context, *ProjectRpcRequest) (*ProjectTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectTemplates not implemented")
}
func (UnimplementedProjectServiceServer) SaveProject(context.Context, *ProjectRpcRequest) (*SaveProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveProject not implemented")
}
func (UnimplementedProjectServiceServer) ReadProject(context.Context, *ProjectRpcRequest) (*ReadProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadProject not implemented")
}
func (UnimplementedProjectServiceServer) UpdateProjectDeleted(context.Context, *ProjectRpcRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectDeleted not implemented")
}
func (UnimplementedProjectServiceServer) UpdateProjectCollected(context.Context, *ProjectRpcRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectCollected not implemented")
}
func (UnimplementedProjectServiceServer) EditProject(context.Context, *EditProjectRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditProject not implemented")
}
func (UnimplementedProjectServiceServer) GetLogBySelfProject(context.Context, *ProjectRpcRequest) (*ProjectLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogBySelfProject not implemented")
}
func (UnimplementedProjectServiceServer) GetNodeList(context.Context, *ProjectRpcRequest) (*ProjectNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeList not implemented")
}
func (UnimplementedProjectServiceServer) FindProjectByMemberId(context.Context, *ProjectRpcRequest) (*FindProjectByMemberIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindProjectByMemberId not implemented")
}
func (UnimplementedProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.ProjectService/Index",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Index(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.ProjectService/GetProjectList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectList(ctx, req.(*ProjectRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.ProjectService/GetProjectTemplates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectTemplates(ctx, req.(*ProjectRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_SaveProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SaveProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.ProjectService/SaveProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SaveProject(ctx, req.(*ProjectRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ReadProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ReadProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.ProjectService/ReadProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ReadProject(ctx, req.(*ProjectRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProjectDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProjectDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.ProjectService/UpdateProjectDeleted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProjectDeleted(ctx, req.(*ProjectRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProjectCollected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProjectCollected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.ProjectService/UpdateProjectCollected",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProjectCollected(ctx, req.(*ProjectRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_EditProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).EditProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.ProjectService/EditProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).EditProject(ctx, req.(*EditProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetLogBySelfProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetLogBySelfProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.ProjectService/GetLogBySelfProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetLogBySelfProject(ctx, req.(*ProjectRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetNodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetNodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.ProjectService/GetNodeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetNodeList(ctx, req.(*ProjectRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_FindProjectByMemberId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).FindProjectByMemberId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.ProjectService/FindProjectByMemberId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).FindProjectByMemberId(ctx, req.(*ProjectRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project.service.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _ProjectService_Index_Handler,
		},
		{
			MethodName: "GetProjectList",
			Handler:    _ProjectService_GetProjectList_Handler,
		},
		{
			MethodName: "GetProjectTemplates",
			Handler:    _ProjectService_GetProjectTemplates_Handler,
		},
		{
			MethodName: "SaveProject",
			Handler:    _ProjectService_SaveProject_Handler,
		},
		{
			MethodName: "ReadProject",
			Handler:    _ProjectService_ReadProject_Handler,
		},
		{
			MethodName: "UpdateProjectDeleted",
			Handler:    _ProjectService_UpdateProjectDeleted_Handler,
		},
		{
			MethodName: "UpdateProjectCollected",
			Handler:    _ProjectService_UpdateProjectCollected_Handler,
		},
		{
			MethodName: "EditProject",
			Handler:    _ProjectService_EditProject_Handler,
		},
		{
			MethodName: "GetLogBySelfProject",
			Handler:    _ProjectService_GetLogBySelfProject_Handler,
		},
		{
			MethodName: "GetNodeList",
			Handler:    _ProjectService_GetNodeList_Handler,
		},
		{
			MethodName: "FindProjectByMemberId",
			Handler:    _ProjectService_FindProjectByMemberId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "project_service.proto",
}
